//Copyright 2020 Marchetti Alfredo. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

#define TERRAIN_DEFINE_GAMEPLAY_TAG(TagName, Tag, Comment) FNativeGameplayTag TagName(UE_PLUGIN_NAME, UE_MODULE_NAME, Tag, Comment, ENativeGameplayTagToken::PRIVATE_USE_MACRO_INSTEAD);

TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_LAYOUT_INITIAL);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_LAYOUT_CENTRAL);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_LAYOUT_BORDER);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_LAYOUT_BORDERCOLLISION);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_LAYOUT_DOOR);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_LAYOUT_DOOR_STARTCORRIDOR);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_LAYOUT_DOOR_ENDCORRIDOR);

TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_TYPE_ROOM);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_TYPE_CORRIDOR);
TERRAINGENERATOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_TERRAIN_CELL_TYPE_WALL);
