//Copyright 2020 Marchetti Alfredo. All Rights Reserved.
#include "Tags/TerrainTags.h"

TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_LAYOUT_INITIAL, "Terrain.Cell.Layout.Initial", "");
TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_LAYOUT_CENTRAL, "Terrain.Cell.Layout.Central", "");
TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_LAYOUT_BORDER, "Terrain.Cell.Layout.Border", "");
TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_LAYOUT_BORDERCOLLISION, "Terrain.Cell.Layout.BorderCollision", "");

TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_LAYOUT_DOOR, "Terrain.Cell.Layout.Door", "");
TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_LAYOUT_DOOR_STARTCORRIDOR, "Terrain.Cell.Layout.Door.StartCorridor", "");
TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_LAYOUT_DOOR_ENDCORRIDOR, "Terrain.Cell.Layout.Door.EndCorridor", "");


TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_TYPE_ROOM, "Terrain.Cell.Type.Room", "");
TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_TYPE_CORRIDOR, "Terrain.Cell.Type.Corridor", "");
TERRAIN_DEFINE_GAMEPLAY_TAG(TAG_TERRAIN_CELL_TYPE_WALL, "Terrain.Cell.Type.Wall", "");
